repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-added-large-files
  - id: end-of-file-fixer
- repo: https://github.com/psf/black
  rev: 26.3.0
  hooks:
  - id: black
- repo: https://github.com/ikamensh/flynt/
  rev: 1.0.6
  hooks:
  - id: flynt
ci:
  autoupdate_commit_msg: 'chore: update pre-commit hooks'
  autoupdate_schedule: monthly
  autofix_commit_msg: 'style: pre-commit fixes'
